name: simple-scan
adopt-info: simple-scan
summary: Document Scanning Application
description: |
  A really easy way to scan both documents and photos from a scanner (e.g. a flatbed scanner).

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

slots:
  # for GtkApplication registration
  simple-scan:
    interface: dbus
    bus: session
    name: org.gnome.SimpleScan

apps:
  simple-scan:
    plugs:
      - network
      - network-control
      - home
      - hardware-observe
      - mount-observe
      - system-observe
      - io-ports-control
      - raw-usb
      #- cups
      #- cups-control
      - avahi-observe
      - avahi-control
    command: usr/bin/simple-scan
    extensions: [ gnome ]
    desktop: usr/share/applications/simple-scan.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

parts:
  libsane:
# ext: updatesnap
#   version-format:
#     format: 'upstream/%M.%m.%R'
    source: https://salsa.debian.org/debian/sane-backends.git
    source-type: git
    source-tag: 'upstream/1.0.27'
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-api-spec=no

  simple-scan:
    after: [libsane]
    source: https://gitlab.gnome.org/GNOME/simple-scan.git
    source-type: git
    source-tag: '42.1'
    source-depth: 1
    plugin: meson
    parse-info: [usr/share/metainfo/simple-scan.appdata.xml]
    meson-parameters:
      - --prefix=/usr
    override-build: |
      sed -i.bak -e 's|Icon=org.gnome.SimpleScan$|Icon=${SNAP}/meta/gui/org.gnome.SimpleScan.svg|g' $CRAFT_PART_SRC/data/simple-scan.desktop.in
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/hicolor/scalable/org.gnome.SimpleScan.svg $CRAFT_PART_INSTALL/meta/gui/
      craftctl default
    build-packages:
      - desktop-file-utils
      - gnome-common
      - intltool
      - libcolord-dev
      - libgusb-dev
      - libpackagekit-glib2-dev
    stage-packages:
      - sane-airscan

  libs:
    plugin: nil
    stage-packages:
      - libgusb2
      - libpackagekit-glib2-18
      - libieee1284-3

  cleanup:
    after: [ libs ]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
